removed initialize method from controller and added init. Added init …
webdreamer25/Zense pull request #10
Opened 2020-11-30 01:22 UTC by webdreamer25

…invocation to composite and module logic that sets modules/components. updated checkUniqueName and setUniqueName.

- remove initialize() method from controller.js and added init() method instead that the module/composite invoke at run time.
- added invocation for controller init to composite.js for modules declared and to module.js for components declared.
- fixed issue with module.js checkUniqueName and component.js setUniqueName that was not working.

2020-12-12 23:47 UTC, yoelolivares requested changes

2020-12-12 23:47 UTC, yoelolivares commented on src/app/scss/behaviors/_progressive-img.scss
> +  // img {
should this commented code stay?

2020-12-13 00:04 UTC, webdreamer25 commented on src/app/scss/behaviors/_progressive-img.scss
> +  // img {
oh should have let you know to ignore any file in src/app directory because that is just to test zense js.

2020-12-13 00:08 UTC, yoelolivares approved these changes

2020-12-13 00:19 UTC, merged